POST http://127.0.0.1/highscore
content-type: application/json

{
	"level": "bar",
	"name": "foo",
	"score": 110,
	"time": 10.7,
	"ghost": [
		{
			"time": 0.0,
			"location": [0.0, 0.1, 0.2]
		},
		{
			"time": 0.5,
			"location": [1.0, 1.1, 1.2]
		},
		{
			"time": 1.0,
			"location": [2.0, 2.1, 2.2]
		}
	]
}